# Generated by Django 6.0.4 on 2026-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name_plural': 'Estados de Pedido'},
        ),
        migrations.AlterField(
            model_name='estado',
            name='codigo',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('FACTURADO', 'Facturado'), ('COBRADO', 'Cobrado')], max_length=20, unique=True),
        ),
    ]
